import 'package:mate/models/blog_model.dart';

List<BlogModel> blogs = [
  BlogModel(username: 'Merry Jane', postDate: DateTime.now(), likes: 15, content: '''Customer churn is one of the major problem for large companies. Due to direct effect on revenues of companies specially in telecom field, companies are seeking to predict potential customer to churn. Therefore finding the factors that causes these churn and countermeasures that should be taken to reduce these potential churn. 
The main goal of our project is to develop an easy & simple model which can assist telecom operator to predict the customers who would most likely churn. Model developed through this project uses machine learning on data platform and builds ways of features' engineering and selection. Standard measures like Area Under Curve(AUC) is adopted to measure the performance of the model along with other method which is Social Network Analysis(SNA), by the way it's accurate up to 93.3% which we can say is a good value. The use of SNA against AUC increased the performance from 84 to 93.3%.'''),
BlogModel(username: 'Merry Jane', postDate: DateTime.now(), likes: 15, content: '''Customer churn is one of the major problem for large companies. Due to direct effect on revenues of companies specially in telecom field, companies are seeking to predict potential customer to churn. Therefore finding the factors that causes these churn and countermeasures that should be taken to reduce these potential churn. 
The main goal of our project is to develop an easy & simple model which can assist telecom operator to predict the customers who would most likely churn. Model developed through this project uses machine learning on data platform and builds ways of features' engineering and selection. Standard measures like Area Under Curve(AUC) is adopted to measure the performance of the model along with other method which is Social Network Analysis(SNA), by the way it's accurate up to 93.3% which we can say is a good value. The use of SNA against AUC increased the performance from 84 to 93.3%.'''),
BlogModel(username: 'Merry Jane', postDate: DateTime.now(), likes: 15, content: '''Customer churn is one of the major problem for large companies. Due to direct effect on revenues of companies specially in telecom field, companies are seeking to predict potential customer to churn. Therefore finding the factors that causes these churn and countermeasures that should be taken to reduce these potential churn. 
The main goal of our project is to develop an easy & simple model which can assist telecom operator to predict the customers who would most likely churn. Model developed through this project uses machine learning on data platform and builds ways of features' engineering and selection. Standard measures like Area Under Curve(AUC) is adopted to measure the performance of the model along with other method which is Social Network Analysis(SNA), by the way it's accurate up to 93.3% which we can say is a good value. The use of SNA against AUC increased the performance from 84 to 93.3%.'''),
BlogModel(username: 'Merry Jane', postDate: DateTime.now(), likes: 15, content: '''Customer churn is one of the major problem for large companies. Due to direct effect on revenues of companies specially in telecom field, companies are seeking to predict potential customer to churn. Therefore finding the factors that causes these churn and countermeasures that should be taken to reduce these potential churn. 
The main goal of our project is to develop an easy & simple model which can assist telecom operator to predict the customers who would most likely churn. Model developed through this project uses machine learning on data platform and builds ways of features' engineering and selection. Standard measures like Area Under Curve(AUC) is adopted to measure the performance of the model along with other method which is Social Network Analysis(SNA), by the way it's accurate up to 93.3% which we can say is a good value. The use of SNA against AUC increased the performance from 84 to 93.3%.'''),
];